import Footer from "@/components/Footer";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "360-lity",
  description: "Generated by create next app",
  icons: {
    icon: "/360-lity.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="px-[3.5rem] md:px-[4.5rem] xl:px-[6rem] h-full">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
