import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/common/Navigation";
import { usePathname } from "next/navigation";
import Footer from "@/components/Footer";
import LayooutView from "./layoout-view";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "360-lity",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/360-lity.svg",
//   },
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayooutView>{children}</LayooutView>
      </body>
    </html>
  );
}
