export const routes = {
  login: "/user/login",
  upload: "/image/upload",
  delete: "/image/delete",
  project: "/project",
  showcase: "/showcase",
  blog: "/blog",
  contact: "/contact",
  about: "/about",
  arvr: "/arvr",
  team: "/team",
  photography: "/photography",
  videography: "/videography",
  animation: "/animation",
  xvt: "/xvt",
};
